file  = ./mpu6050_app.c 
file2 = ./my_mpu6050_app.c 

compile:
	arm-none-linux-gnueabi-gcc $(file) -o output
	cp output ~/new_fs4412/rootfs/

my_compile:
	arm-none-linux-gnueabi-gcc $(file2) -o output
	cp output ~/new_fs4412/rootfs/
